export const busses = [
	{
		id: 'bus-001',
		name: 'АвтоЛюкс Київ → Львів',
		description: 'Комфортна поїздка з Києва до Львова тривалістю 6 год 15 хв.',
		image: 'https://ukraine-kiev-tour.com/images/2017/flixbus.jpg',
		location: 'Київ → Львів',
		pricePerTicket: 480,
		rating: 4.5,
		numberOfReviews: 132,
		amenities: ['Wi-Fi', 'Кондиціонер', 'Розетки', 'Туалет'],
	},
	{
		id: 'bus-002',
		name: 'Gunsel Львів → Одеса',
		description: "Нічний маршрут із м'якими сидіннями та шторками для сну.",
		image:
			'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk5l9gCBYlErpdraf-sFM7EKOe20uOCRbi1w&s',
		location: 'Львів → Одеса',
		pricePerTicket: 600,
		rating: 4.6,
		numberOfReviews: 98,
		amenities: ['Wi-Fi', 'Туалет', 'Завіси', 'Пледи'],
	},
	{
		id: 'bus-003',
		name: 'Еколайнс Харків → Київ',
		description: 'Щоденний ранковий рейс з Харкова до столиці.',
		image:
			'https://www.scania.com/content/dam/group/products-and-services/buses-and-coaches/touring/scania-touring-24207-003_16-7.jpg',
		location: 'Харків → Київ',
		pricePerTicket: 450,
		rating: 4.3,
		numberOfReviews: 87,
		amenities: ['Wi-Fi', 'Туалет'],
	},
	{
		id: 'bus-004',
		name: 'АвтоЛюкс Дніпро → Івано-Франківськ',
		description: 'Денний рейс через мальовничі пейзажі України.',
		image:
			'https://www.sustainable-bus.com/wp-content/uploads/2019/07/volvo-electric-bus.jpg',
		location: 'Дніпро → Івано-Франківськ',
		pricePerTicket: 550,
		rating: 4.2,
		numberOfReviews: 74,
		amenities: ['Кондиціонер', 'Wi-Fi', 'Розетки'],
	},
	{
		id: 'bus-005',
		name: 'Gunsel Київ → Чернівці',
		description: 'Нічний комфорт-клас із зарядками для гаджетів.',
		image:
			'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu3ltp9iAank1tnzFv4zayMojKIpNLsYb-5Pbbv0UDtEDO7gchadM4TEDt71UrtX8EpJk&usqp=CAU',
		location: 'Київ → Чернівці',
		pricePerTicket: 490,
		rating: 4.4,
		numberOfReviews: 65,
		amenities: ['Wi-Fi', 'Завіси', 'USB зарядка'],
	},
]
