export const hotels = [
	{
		id: 'hotel-001',
		name: 'Fairmont Grand Hotel Kyiv',
		description: 'Розкішний готель у центрі Києва, поруч з Хрещатиком.',
		image:
			'https://ik.imgkit.net/3vlqs5axxjf/external/ik-seo/https://www.cfmedia.vfmleonardo.com/imageRepo/6/0/99/931/813/a596_ho_00_p_3000x2250_O/Fairmont-Grand-Hotel-Kyiv-Exterior.jpg?tr=w-656%2Ch-390%2Cfo-auto',
		location: 'Київ, Україна',
		pricePerNight: 250,
		rating: 4.7,
		numberOfReviews: 410,
		amenities: ['Wi‑Fi', 'Спа', 'Ресторан', 'Паркінг'],
	},
	{
		id: 'hotel-002',
		name: 'Nadiya Hotel Ivano-Frankivsk',
		description: 'Сучасний готель в Івано‑Франківську з зручним розташуванням.',
		image:
			'https://ik.imgkit.net/3vlqs5axxjf/external/ik-seo/https://media.iceportal.com/82807/photos/69732754_XL/Nadiya-Hotel-Exterior.jpg?tr=w-780%2Ch-437%2Cfo-auto',
		location: 'Івано‑Франківськ, Україна',
		pricePerNight: 90,
		rating: 4.3,
		numberOfReviews: 150,
		amenities: ['Wi‑Fi', 'Ресторан', 'Кондиціонер'],
	},
	{
		id: 'hotel-003',
		name: 'Atlas Deluxe Hotel Lviv',
		description: 'Готель у старому місті Львова з елегантним дизайном.',
		image:
			'https://ik.imgkit.net/3vlqs5axxjf/external/ik-seo/https://www.cfmedia.vfmleonardo.com/imageRepo/2/0/65/481/102/SKLWOATL01_O/Atlas-Deluxe-Hotel-Lviv-Exterior.jpg?tr=w-780%2Ch-437%2Cfo-auto',
		location: 'Львів, Україна',
		pricePerNight: 130,
		rating: 4.6,
		numberOfReviews: 320,
		amenities: ['Wi‑Fi', 'Бар', 'Ресторан', 'Спа'],
	},
	{
		id: 'hotel-004',
		name: 'Nemo Hotel & SPA Odesa',
		description: 'Курорт біля моря з басейнами та SPA в Одесі.',
		image:
			'https://images.trvl-media.com/lodging/9000000/8790000/8782900/8782898/c14e2771.jpg?impolicy=resizecrop&rw=1200&ra=fit',
		location: 'Одеса, Україна',
		pricePerNight: 160,
		rating: 4.5,
		numberOfReviews: 280,
		amenities: ['Басейн', 'SPA', 'Пляж', 'Wi‑Fi'],
	},
	{
		id: 'hotel-005',
		name: 'Premier Palace Hotel Kyiv',
		description: 'Готель класу люкс з конференц-залами та видом на місто.',
		image:
			'https://ik.imgkit.net/3vlqs5axxjf/external/https://www.cfmedia.vfmleonardo.com/imageRepo/7/0/151/292/367/Premier_Palace_Hotel_Kyiv_building_facade_O.jpg?tr=w-940%2Ch-529%2Cfo-auto%2Cdi-ami-fallback.png',
		location: 'Київ, Україна',
		pricePerNight: 200,
		rating: 4.4,
		numberOfReviews: 220,
		amenities: ['Wi‑Fi', 'Конференц-зали', 'Спортзал', 'Ресторан'],
	},
	{
		id: 'hotel-006',
		name: 'Opera Hotel Kyiv',
		description: 'Готель поруч з оперним театром у центрі Києва.',
		image:
			'https://ik.imgkit.net/3vlqs5axxjf/external/ik-seo/https://www.cfmedia.vfmleonardo.com/imageRepo/1/0/28/70/673/fasad_day2_O/Opera-Hotel-Exterior.jpg?tr=w-780%2Ch-437%2Cfo-auto',
		location: 'Київ, Україна',
		pricePerNight: 120,
		rating: 4.2,
		numberOfReviews: 180,
		amenities: ['Wi‑Fi', 'Сніданок', 'Кондиціонер'],
	},
	{
		id: 'hotel-007',
		name: 'Hotel Ukraine Kyiv',
		description: 'Чотиризірковий готель на Інститутській, історична будівля.',
		image:
			'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/17-07-02-Maidan_Nezalezhnosti_RR74356.jpg/800px-17-07-02-Maidan_Nezalezhnosti_RR74356.jpg',
		location: 'Київ, Україна',
		pricePerNight: 140,
		rating: 4.3,
		numberOfReviews: 400,
		amenities: ['Wi‑Fi', 'Ресторан', 'Паркінг', 'Конференц-зали'],
	},
	{
		id: 'hotel-008',
		name: 'Ukraine Hotel Dnipro',
		description: 'Відомий готель на центральній площі Дніпра.',
		image:
			'https://ik.imgkit.net/3vlqs5axxjf/external/ik-seo/https://media.iceportal.com/40844/photos/4590519_XL/Grand-Hotel-Ukraine-Exterior.jpg?tr=w-656%2Ch-390%2Cfo-auto',
		location: 'Дніпро, Україна',
		pricePerNight: 110,
		rating: 4.1,
		numberOfReviews: 190,
		amenities: ['Wi‑Fi', 'Ресторан', 'Паркінг'],
	},
	{
		id: 'hotel-009',
		name: 'InterContinental Kyiv',
		description: 'П’ятизірковий інтернаціональний готель у центрі Києва.',
		image:
			'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2c/01/81/a9/intercontinental-kyiv.jpg?w=900&h=-1&s=1',
		location: 'Київ, Україна',
		pricePerNight: 230,
		rating: 4.8,
		numberOfReviews: 500,
		amenities: ['Wi‑Fi', 'Спа', 'Басейн', 'Ресторан', 'Паркінг'],
	},
	{
		id: 'hotel-010',
		name: 'Atlas Deluxe Night View Lviv',
		description: 'Готель у Львові з атмосферою старовинного міста.',
		image:
			'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/bd/cd/5b/hotel-atlas-deluxe.jpg?w=900&h=-1&s=1',
		location: 'Львів, Україна',
		pricePerNight: 125,
		rating: 4.5,
		numberOfReviews: 260,
		amenities: ['Wi‑Fi', 'Бар', 'Центр міста', 'Ресторан'],
	},
]
